package middleware

import (
	"context"
	"net/http"
	"strconv"
	"time"

	"github.com/go-chi/chi/v5"
	chimw "github.com/go-chi/chi/v5/middleware"
	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promauto"
	"github.com/prometheus/client_golang/prometheus/promhttp"
)

var (
	httpRequestsTotal = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Name: "velox_http_requests_total",
			Help: "Total HTTP requests by method, path pattern, and status code.",
		},
		[]string{"method", "path", "status"},
	)

	httpRequestDuration = promauto.NewHistogramVec(
		prometheus.HistogramOpts{
			Name:    "velox_http_request_duration_seconds",
			Help:    "HTTP request latency in seconds.",
			Buckets: []float64{0.001, 0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1, 2.5, 5},
		},
		[]string{"method", "path", "status"},
	)

	httpRequestsInFlight = promauto.NewGauge(
		prometheus.GaugeOpts{
			Name: "velox_http_requests_in_flight",
			Help: "Current number of HTTP requests being processed.",
		},
	)

	billingCyclesTotal = promauto.NewCounter(
		prometheus.CounterOpts{
			Name: "velox_billing_cycles_total",
			Help: "Total billing cycles executed.",
		},
	)

	// idempotencyCacheErrors counts idempotency-layer DB failures by stage.
	// Non-zero means the idempotency guarantee lapsed: a "reserve" failure
	// fell open (the handler ran without a claim, so a concurrent/retried
	// request could re-execute the side effect), and a "finalize" failure
	// means the response wasn't cached (a retry under the same key re-runs the
	// handler). Operators should alert on any sustained rate here.
	idempotencyCacheErrors = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Name: "velox_idempotency_cache_errors_total",
			Help: "Idempotency cache DB errors by stage (reserve|finalize).",
		},
		[]string{"stage"},
	)

	invoicesGenerated = promauto.NewCounter(
		prometheus.CounterOpts{
			Name: "velox_invoices_generated_total",
			Help: "Total invoices generated by the billing engine.",
		},
	)

	usageEventsIngested = promauto.NewCounter(
		prometheus.CounterOpts{
			Name: "velox_usage_events_ingested_total",
			Help: "Total usage events ingested.",
		},
	)

	billingCycleDuration = promauto.NewHistogram(
		prometheus.HistogramOpts{
			Name:    "velox_billing_cycle_duration_seconds",
			Help:    "Duration of billing cycle runs in seconds.",
			Buckets: []float64{0.1, 0.5, 1, 2.5, 5, 10, 30, 60, 120, 300},
		},
	)

	billingCycleErrors = promauto.NewCounter(
		prometheus.CounterOpts{
			Name: "velox_billing_cycle_errors_total",
			Help: "Total billing cycle errors.",
		},
	)

	paymentCharges = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Name: "velox_payment_charges_total",
			Help: "Total payment charges by result.",
		},
		[]string{"result"},
	)

	webhookDeliveries = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Name: "velox_webhook_deliveries_total",
			Help: "Total outbound webhook deliveries by status.",
		},
		[]string{"status"},
	)

	dunningRunsProcessed = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Name: "velox_dunning_runs_processed_total",
			Help: "Total dunning runs processed by outcome.",
		},
		[]string{"outcome"},
	)

	creditOperations = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Name: "velox_credit_operations_total",
			Help: "Total credit operations by type.",
		},
		[]string{"type"},
	)

	autoChargeRetries = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Name: "velox_auto_charge_retries_total",
			Help: "Total auto-charge retries by result.",
		},
		[]string{"result"},
	)

	reconcilerSweeps = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Name: "velox_reconciler_sweeps_total",
			Help: "Recovery reconciler sweeps by reconciler, mode, and outcome (run|advanced|error). 'run' increments every tick (liveness); 'advanced'/'error' carry the per-tick counts.",
		},
		[]string{"reconciler", "mode", "outcome"},
	)

	stripeBreakerState = promauto.NewGauge(
		prometheus.GaugeOpts{
			Name: "velox_stripe_breaker_state",
			Help: "Global circuit breaker state for Stripe calls. 0=closed, 1=half_open, 2=open.",
		},
	)

	// parkedInvoices is the alerting surface for ADR-107. A parked invoice is
	// money we may or may not have taken, that no charge path will touch and
	// that no sweep will resolve — it needs a person. Until now "stuck and
	// loud" was log-only, which is not loud: nothing counted them, so nothing
	// could alert on them and an operator had no way to find them. Alert on
	// this being non-zero, and on it growing.
	parkedSearchErrors = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Name: "velox_parked_search_errors_total",
			Help: "ADR-108 parked-invoice search failures by mode and class (not_offered = provider refuses Search for this account; transient = retried after cool-off).",
		},
		[]string{"mode", "class"},
	)

	parkedInvoices = promauto.NewGaugeVec(
		prometheus.GaugeOpts{
			Name: "velox_parked_invoices",
			Help: "Invoices whose charge attempt could not be identified with the provider (ADR-107), by disposition. open = still awaiting an operator decision; written_off = already decided, retained only because the ADR-108 search may still name the PaymentIntent. Alert on `open` growing — summing both hides a decision that was already made.",
		},
		[]string{"mode", "disposition"},
	)

	scheduledCleanupRows = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Name: "velox_scheduled_cleanup_rows_total",
			Help: "Rows purged by scheduled cleanup tasks, labeled by target table.",
		},
		[]string{"table"},
	)

	leaderLeaseLost = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Name: "velox_leader_lease_lost_total",
			Help: "Ticks whose leader lease was lost mid-tick (ADR-114), by role and reason. heartbeat = the holder could not renew within the abandon window and cancelled its own work; release = the release UPDATE found the row taken over. Any non-zero rate means a role ran two overlapping ticks' worth of wall-clock somewhere — the fence and row-CAS kept it correct, but look at why (frozen process, DB stall, pooler).",
		},
		[]string{"role", "reason"},
	)
)

// RecordLeaderLeaseLost counts a lost lease (leader.LostFunc adapter).
func RecordLeaderLeaseLost(role, reason string) {
	leaderLeaseLost.WithLabelValues(role, reason).Inc()
}

// LeaderStatusRow is one role's row from the leader_status view, as the
// metrics collector needs it.
type LeaderStatusRow struct {
	Role               string
	Held               bool
	HasTicked          bool
	LastTickAgeSeconds float64
	Paused             bool
}

// leaderStatusCollector exposes leader_leases as gauges on every scrape —
// a query per scrape, not a cache, because a cached "last tick 30s ago"
// is exactly the lie an operator alerts on. velox_leader_last_tick_age_seconds
// is the cluster fact (WHEN did the role last finish anywhere); the
// per-replica velox_scheduler_last_run_timestamp_seconds only says this
// replica's loop is alive.
type leaderStatusCollector struct {
	query   func(context.Context) ([]LeaderStatusRow, error)
	age     *prometheus.Desc
	held    *prometheus.Desc
	paused  *prometheus.Desc
	scrapeE *prometheus.Desc
}

// RegisterLeaderStatus wires the leader_status collector. Call once at
// boot; a second call panics (duplicate registration), which is the right
// outcome for a double-wire.
func RegisterLeaderStatus(query func(context.Context) ([]LeaderStatusRow, error)) {
	prometheus.MustRegister(&leaderStatusCollector{
		query:   query,
		age:     prometheus.NewDesc("velox_leader_last_tick_age_seconds", "Seconds since the role's last completed tick on ANY replica (leader_leases.last_tick_ended_at). Absent until the role has ticked once. Alert when it exceeds a few multiples of the role's interval — that is the cluster-wide stall signal a single replica's liveness gauge cannot give.", []string{"role"}, nil),
		held:    prometheus.NewDesc("velox_leader_held", "1 while some replica holds the role's lease (a tick is running), else 0.", []string{"role"}, nil),
		paused:  prometheus.NewDesc("velox_leader_paused", "1 while the role is paused by an operator (leader_pause), else 0.", []string{"role"}, nil),
		scrapeE: prometheus.NewDesc("velox_leader_status_scrape_errors_total", "Scrapes on which leader_status could not be read (counts 1 on the failing scrape, so a sustained failure reads as a flat 1).", nil, nil),
	})
}

func (c *leaderStatusCollector) Describe(ch chan<- *prometheus.Desc) {
	ch <- c.age
	ch <- c.held
	ch <- c.paused
	ch <- c.scrapeE
}

func (c *leaderStatusCollector) Collect(ch chan<- prometheus.Metric) {
	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Second)
	defer cancel()
	rows, err := c.query(ctx)
	if err != nil {
		ch <- prometheus.MustNewConstMetric(c.scrapeE, prometheus.GaugeValue, 1)
		return
	}
	ch <- prometheus.MustNewConstMetric(c.scrapeE, prometheus.GaugeValue, 0)
	for _, r := range rows {
		if r.HasTicked {
			ch <- prometheus.MustNewConstMetric(c.age, prometheus.GaugeValue, r.LastTickAgeSeconds, r.Role)
		}
		ch <- prometheus.MustNewConstMetric(c.held, prometheus.GaugeValue, b2f(r.Held), r.Role)
		ch <- prometheus.MustNewConstMetric(c.paused, prometheus.GaugeValue, b2f(r.Paused), r.Role)
	}
}

func b2f(b bool) float64 {
	if b {
		return 1
	}
	return 0
}

// RecordStripeBreakerState updates the global breaker state gauge. Called
// from the breaker's OnStateChange hook. Values mirror gobreaker's semantics:
// 0=closed (normal), 1=half_open (probing), 2=open (rejecting).
func RecordStripeBreakerState(state string) {
	var v float64
	switch state {
	case "half_open":
		v = 1
	case "open":
		v = 2
	}
	stripeBreakerState.Set(v)
}

// RecordParkedSearchError counts ADR-108 search-and-adopt failures by class.
// "not_offered" is the provider refusing the Search API for an account (those
// tenants' parked invoices cannot self-resolve — the one CRITICAL log names
// it); "transient" is rate limits / 5xx / network, which retry after the
// cool-off. Distinct from the parked gauge so "search never works here" pages
// differently from "nothing is parked".
func RecordParkedSearchError(mode, class string) {
	parkedSearchErrors.WithLabelValues(mode, class).Inc()
}

// RecordParkedInvoices publishes the count of invoices parked by ADR-107 for
// the given mode. Called from the payment reconciler each tick — the sweep that
// deliberately no longer PROCESSES them is still the right place to REPORT
// them, so excluding them from the queue did not also make them invisible.
func RecordParkedInvoices(mode, disposition string, n int) {
	parkedInvoices.WithLabelValues(mode, disposition).Set(float64(n))
}

// Metrics returns middleware that records HTTP request metrics.
func Metrics() func(http.Handler) http.Handler {
	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			if r.URL.Path == "/metrics" || r.URL.Path == "/health" {
				next.ServeHTTP(w, r)
				return
			}

			httpRequestsInFlight.Inc()
			defer httpRequestsInFlight.Dec()

			start := time.Now()
			ww := chimw.NewWrapResponseWriter(w, r.ProtoMajor)
			next.ServeHTTP(ww, r)

			status := strconv.Itoa(ww.Status())
			path := routeLabel(r)
			method := methodLabel(r.Method)
			duration := time.Since(start).Seconds()

			httpRequestsTotal.WithLabelValues(method, path, status).Inc()
			httpRequestDuration.WithLabelValues(method, path, status).Observe(duration)
		})
	}
}

// MetricsHandler returns the Prometheus metrics HTTP handler.
func MetricsHandler() http.Handler {
	return promhttp.Handler()
}

// RecordBillingCycle records billing cycle metrics.
func RecordBillingCycle(generated int) {
	billingCyclesTotal.Inc()
	invoicesGenerated.Add(float64(generated))
}

// RecordUsageIngested records usage event ingestion.
func RecordUsageIngested(count int) {
	usageEventsIngested.Add(float64(count))
}

// RecordBillingCycleDuration records how long a billing cycle took.
func RecordBillingCycleDuration(seconds float64) {
	billingCycleDuration.Observe(seconds)
}

// RecordBillingCycleError increments the billing cycle error counter.
func RecordBillingCycleError() {
	billingCycleErrors.Inc()
}

// RecordPaymentCharge records a payment charge result ("succeeded" or "failed").
func RecordPaymentCharge(result string) {
	paymentCharges.WithLabelValues(result).Inc()
}

// RecordWebhookDelivery records a webhook delivery status ("succeeded", "failed", or "pending").
func RecordWebhookDelivery(status string) {
	webhookDeliveries.WithLabelValues(status).Inc()
}

// RecordDunningRun records a processed dunning run outcome ("succeeded" or
// "failed"). The outcome split backs the runbook's dunning-machinery alert
// on {outcome="failed"} — without it, failed runs had zero metric visibility.
func RecordDunningRun(outcome string) {
	dunningRunsProcessed.WithLabelValues(outcome).Inc()
}

// RecordCreditOperation records a credit operation by type ("grant", "usage", "expiry", "adjustment").
func RecordCreditOperation(opType string) {
	creditOperations.WithLabelValues(opType).Inc()
}

// RecordAutoChargeRetry records an auto-charge retry result ("succeeded" or "failed").
func RecordAutoChargeRetry(result string) {
	autoChargeRetries.WithLabelValues(result).Inc()
}

// RecordReconcilerSweep records one recovery-reconciler sweep: a 'run' tick
// (always, so operators can alert on a reconciler that stops running), plus the
// items advanced and per-row errors this tick. `mode` is "live"/"test".
// Powers per-reconciler dashboards/alerts (e.g. a stuck tax-reversal backlog) —
// previously only auto-charge was metered.
func RecordReconcilerSweep(reconciler, mode string, advanced, errs int) {
	reconcilerSweeps.WithLabelValues(reconciler, mode, "run").Inc()
	if advanced > 0 {
		reconcilerSweeps.WithLabelValues(reconciler, mode, "advanced").Add(float64(advanced))
	}
	if errs > 0 {
		reconcilerSweeps.WithLabelValues(reconciler, mode, "error").Add(float64(errs))
	}
}

// RecordScheduledCleanup records rows purged by a scheduled cleanup task.
// Label values match the target table (e.g. "idempotency_keys",
// "payment_tokens") so operators can alert per-table on sudden surges.
func RecordScheduledCleanup(table string, rows int) {
	if rows <= 0 {
		return
	}
	scheduledCleanupRows.WithLabelValues(table).Add(float64(rows))
}

// unmatchedRoute is the path label for any request chi did not route to a
// registered pattern (404/405 at the root, unknown verbs). One constant, so
// a scanner walking /wp-admin, /.env, /phpmyadmin... creates ONE series, not
// one per probe. Same word audit_detector.go uses for the same situation.
const unmatchedRoute = "unmatched"

// routeLabel returns the chi ROUTE PATTERN for the request (e.g.
// /v1/customers/{id}) — a closed set: registered patterns, one "prefix/*"
// per Mount, and unmatchedRoute. It must be read synchronously after
// next.ServeHTTP, while the *chi.Context is still checked out (chi puts it
// back to the pool only after the mux handler returns); router.go's
// requestLogger and audit_detector.go already read it this way.
//
// Why not the raw path: client_golang never evicts vec children, so every
// distinct label value is ~2 KB of heap for the life of the process. The
// previous sanitizePath heuristic (rewrite vlx_-prefixed or >20-char
// segments) left every other client-chosen path — every 404 probe — as its
// own series: attacker-controlled memory growth, measured at 900 probes →
// 900 series.
func routeLabel(r *http.Request) string {
	if rctx := chi.RouteContext(r.Context()); rctx != nil {
		if p := rctx.RoutePattern(); p != "" {
			return p
		}
	}
	return unmatchedRoute
}

// methodLabel bounds the method axis to the verbs chi routes plus "other";
// the method is client-chosen text and was the second unbounded label.
func methodLabel(m string) string {
	switch m {
	case http.MethodConnect, http.MethodDelete, http.MethodGet, http.MethodHead,
		http.MethodOptions, http.MethodPatch, http.MethodPost, http.MethodPut, http.MethodTrace:
		return m
	}
	return "other"
}

// sanitizePath normalizes a raw URL path by replacing ID-shaped segments with
// :id. It is used by tracing.go for span names — otelhttp names spans BEFORE
// routing, so the route pattern is not available there. It is NOT used for
// metric labels any more (see routeLabel).
func sanitizePath(path string) string {
	// Common patterns: /v1/customers/vlx_cus_abc123 → /v1/customers/:id
	parts := splitPath(path)
	for i, part := range parts {
		if isID(part) {
			parts[i] = ":id"
		}
	}
	return joinPath(parts)
}

func splitPath(path string) []string {
	var parts []string
	current := ""
	for _, c := range path {
		if c == '/' {
			if current != "" {
				parts = append(parts, current)
				current = ""
			}
		} else {
			current += string(c)
		}
	}
	if current != "" {
		parts = append(parts, current)
	}
	return parts
}

func joinPath(parts []string) string {
	result := ""
	for _, p := range parts {
		result += "/" + p
	}
	if result == "" {
		return "/"
	}
	return result
}

func isID(s string) bool {
	// Velox IDs start with vlx_ prefix
	if len(s) > 4 && s[:4] == "vlx_" {
		return true
	}
	// UUIDs and other long hex strings
	if len(s) > 20 {
		return true
	}
	return false
}

// schedulerLastRunTimestamp backs the runbook's "scheduler is alive" alert:
// `time() - velox_scheduler_last_run_timestamp_seconds > 2 * interval`.
// Pre-2026-07-06 the runbook told operators to alert on scheduler last-run
// age with NO exported metric (only /health/ready encoded it).
var schedulerLastRunTimestamp = promauto.NewGauge(
	prometheus.GaugeOpts{
		Name: "velox_scheduler_last_run_timestamp_seconds",
		Help: "Unix timestamp of the billing scheduler's last completed tick. Alert when time() - this > 2x the scheduler interval.",
	},
)

// RecordSchedulerTick stamps the scheduler-liveness gauge; called by the
// same hook that feeds /health/ready.
func RecordSchedulerTick() {
	schedulerLastRunTimestamp.SetToCurrentTime()
}

// RegisterQueueDepthGauges exports the queue-depth gauges the shipped
// Grafana dashboard and runbook alert on. Pre-2026-07-06 the dashboard
// queried velox_email_outbox_pending / velox_webhook_outbox_pending /
// velox_dunning_active_runs masked by `OR vector(0)` — gauges the binary
// never exported, so the panels flatlined at 0 through a real backlog.
//
// Gauges resolve at SCRAPE time via one COUNT each (cheap: partial/status
// indexes; 3s cap). A query failure reports -1 — visibly wrong rather than
// a healthy-looking 0.
func RegisterQueueDepthGauges(count func(query string) (float64, error)) {
	gauge := func(name, help, query string) {
		promauto.NewGaugeFunc(prometheus.GaugeOpts{Name: name, Help: help}, func() float64 {
			n, err := count(query)
			if err != nil {
				return -1
			}
			return n
		})
	}
	gauge("velox_email_outbox_pending",
		"Emails waiting for the outbox dispatcher (status='pending'). -1 = metric query failed.",
		`SELECT COUNT(*) FROM email_outbox WHERE status = 'pending'`)
	gauge("velox_webhook_outbox_pending",
		"Outbound webhook events waiting for the outbox dispatcher (status='pending'). -1 = metric query failed.",
		`SELECT COUNT(*) FROM webhook_outbox WHERE status = 'pending'`)
	gauge("velox_dunning_active_runs",
		"Dunning runs currently active. -1 = metric query failed.",
		`SELECT COUNT(*) FROM invoice_dunning_runs WHERE state = 'active'`)
	gauge("velox_creditnote_pending_issue_drafts",
		"Clawback credit-note drafts awaiting issue (issue_pending, status='draft') — includes drafts legitimately deferred behind an in-flight source payment (ADR-059); alert on sustained growth/age, not presence. -1 = metric query failed.",
		`SELECT COUNT(*) FROM credit_notes WHERE issue_pending AND status = 'draft'`)
	gauge("velox_creditnote_pending_tax_reversals",
		"Issued credit notes whose upstream tax reversal is still owed and being retried (tax_reversal_pending). Presence is normal for a tick or two; a row here for >24h means the provider keeps rejecting it — runbook tier-2. -1 = metric query failed.",
		`SELECT COUNT(*) FROM credit_notes WHERE tax_reversal_pending AND status = 'issued'`)
	gauge("velox_invoice_pending_tax_reversals",
		"Voided stripe_tax invoices with a committed upstream tax transaction and no confirmed reversal (tax_reversed_at IS NULL) — the invoice-side owed reversals the #310 sweep re-drives. Alert on age, not presence. -1 = metric query failed.",
		`SELECT COUNT(*) FROM invoices WHERE status = 'voided' AND tax_provider = 'stripe_tax' AND COALESCE(tax_transaction_id,'') <> '' AND tax_reversed_at IS NULL`)
}
